### ISSUE TITLE
Heroku listed as malicious in mac

### ISSUE THREAD

**Issue by jsltran3** [learn-co-curriculum/react-hooks-phase-2-project#4]
### Canvas Link

https://github.com/learn-co-curriculum/react-hooks-phase-2-project

### Concern

Hi there, 

I went through with Heroku to deploy my app, but found that Apple has marked it as malicious due to a recent data breach. As such I cannot install it on my mac. 

I was wondering if you can offer other free alternatives. 

Thanks,
Joe

### Suggested Changes

Provide more alternatives

**Comment by lizbur10** [comment]
Hi @jsltran3 - I'm so sorry to hear you ran into this problem. Were you able to resolve the issue?

**Comment by lizbur10** [comment]
Hi again - Heroku is discontinuing its free offerings later this fall so we will be updating the curriculum soon to use a different solution, but it will take some time to implement those changes. I'm going to go ahead and close this issue, but know that the situation will be addressed. Apologies for the inconvenience.

Thanks for contributing to the Flatiron School curriculum 💙
